name: Sync to GitLab

on:
  push:
    branches: [ main, master ] # سيعمل التحديث تلقائياً عند الـ Push على هذه الفروع

jobs:
  sync-code:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Push Code to GitLab Docker Server
        run: |
          # المزامنة المباشرة والدفع القسري لسيرفر الـ Docker الخاص بك
          git push --force --prune http://aliqannan:${{ secrets.GITLAB_PASSWORD }}@91.134.134.106/aliqannan/startup-server.git refs/remotes/origin/*:refs/heads/* refs/tags/*:refs/tags/*
